controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

   
    rigid_pose_broadcaster:
      type: chainable_controllers_demo/RigidPoseBroadcaster

    broyden_controller:
      type: chainable_controllers_demo/BroydenController

    kalman_controller:
      type: chainable_controllers_demo/KalmanController
      parameters:
        interfaces:
          - rigid_pose_broadcaster/pose.x
          - rigid_pose_broadcaster/pose.y
          - rigid_pose_broadcaster/pose.theta
          - broyden_controller/vel.v
          - broyden_controller/vel.w

