controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

    kalman_controller:
      type: chainable_controllers_demo/KalmanController

    broyden_controller:
      type: chainable_controllers_demo/BroydenController

    rigid_pose_broadcaster:
      type: chainable_controllers_demo/RigidPoseBroadcaster

# PARAMETERS


broyden_controller:
  ros__parameters:
    interfaces:
      - kalman_controller/vel.v
      - kalman_controller/vel.w

rigid_pose_broadcaster:
  ros__parameters:
    interfaces:
      - kalman_controller/pose.x
      - kalman_controller/pose.y
      - kalman_controller/pose.theta
